### PR TITLE
Prevent crash when the document kind is unknown

### LINKED ISSUE #7: Migration discovery should ignore missing mappings
Hit a segfault working on Rode after renaming a document kind, but without deleting the prior index:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x171c632]

goroutine 1 [running]:
github.com/rode/es-index-manager/indexmanager.(*migrator).GetMigrations(0xc000148380, 0x20440f0, 0xc00019c000, 0xc000110c00, 0xc00013c1a0, 0xc00039f380, 0x1edfb11, 0x8)
	/Users/alex/go/pkg/mod/github.com/rode/es-index-manager@v0.1.2/indexmanager/migration.go:82 +0x352
github.com/rode/es-index-manager/indexmanager.(*migrationOrchestrator).RunMigrations(0xc0001563c0, 0x20440f0, 0xc00019c000, 0xf, 0xc000110a20)
	/Users/alex/go/pkg/mod/github.com/rode/es-index-manager@v0.1.2/indexmanager/orchestrator.go:43 +0x88
github.com/rode/es-index-manager/indexmanager.(*indexManager).Initialize(0xc0001127b0, 0x20440f0, 0xc00019c000, 0xc000110a20, 0x32cf583)
	/Users/alex/go/pkg/mod/github.com/rode/es-index-manager@v0.1.2/indexmanager/index_manager.go:69 +0xe2
github.com/rode/rode/server.(*rodeServer).initialize(0xc00014a300, 0x20440f0, 0xc00019c000, 0x0, 0xc00039f738)
	/Users/alex/Developer/liatrio/rode/rode/server/server.go:138 +0x9c
github.com/rode/rode/server.NewRodeServer(0xc0001109c0, 0x205add8, 0xc0001340e0, 0x20445f8, 0xc0001340f0, 0x2032740, 0xc0001563d8, 0x2046d78, 0xc0001483c0, 0x2056958, ...)
	/Users/alex/Developer/liatrio/rode/rode/server/server.go:64 +0x171
main.main()
	/Users/alex/Developer/liatrio/rode/rode/main.go:124 +0x130c
exit status 2
```

As part of determining which migrations need to run, we parse each index name. Without a matching document kind in the registry, that code [returns nil](https://github.com/rode/es-index-manager/blob/29ac7555ebcc5460a756da74579028be1b990d5f/indexmanager/registry.go#L101-L103), which is then [dereferenced](https://github.com/rode/es-index-manager/blob/29ac7555ebcc5460a756da74579028be1b990d5f/indexmanager/migration.go#L82)

### LINKED ISSUE #8: Double logging index name when creating index
We add `index` as a field twice to the logger, surprisingly it's preserved in the log output:
```
2021-06-15T13:56:23.809-0400	INFO	IndexManager.CreateIndex	indexmanager/index_repository.go:111	index created	{"index": "rode-v1alpha1-policy-groups", "index": "rode-v1alpha1-policy-groups"}
```

https://github.com/rode/es-index-manager/blob/29ac7555ebcc5460a756da74579028be1b990d5f/indexmanager/index_repository.go#L111

### PR DESCRIPTION
**Pull request by alexashley**
This usually happens during development -- if a new index is added in one branch, switching to another will crash the application when it's determining which migrations to run. We look at the registered mappings in order to know what a valid document kind is when parsing the index name. 

It could also happen in a production environment if a newer version of Rode was deployed and then reverted. 

An easy way to reproduce is to create an index with the right settings and start Rode:
```shell
curl -X PUT \
  --url $ELASTICSEARCH_URL/rode-v1alpha1-whoops \
  --header 'Content-Type: application/json' \
  --data '{
	"mappings": {
		"_meta": {
			"type": "rode"
		}
	}
}'
``` 

Closes #7 
Closes #8

### CODE REVIEW

File: indexmanager/registry.go [hunk 1]
```diff
@@ -99,7 +100,7 @@ func (mr *mappingsRegistry) ParseIndexName(indexName string) *IndexName {
 	}
 
 	if documentKind == "" {
-		return nil
+		return nil, false
```
Comment (mrparkers) [inline indexmanager/registry.go]: maybe I'm missing some context here, but why not just keep the `nil` return and do a check for it when consuming this function?  it looks like we only ever return either `nil, false` or `(not nil), true`.

Comment (alexashley) [reply indexmanager/registry.go]: That's what I had originally, but I thought using the `value, ok` pattern would be a little more explicit. I'll switch it back.

**Review by mrparkers — APPROVED** [review]
